# Generated by Django 5.0.6 on 2024-07-03 16:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField(default=datetime.datetime.now)),
                ('operating_time', models.IntegerField(default=0)),
                ('work_order', models.CharField(default='', max_length=100)),
                ('date_ordered', models.DateField(default=datetime.datetime.now)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_organization', to='accounts.servicecompany')),
                ('service_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_as_service_company', to='accounts.servicecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetype')),
            ],
        ),
    ]
