# Generated by Django 5.0.6 on 2024-07-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_organization', to='maintenance.organization'),
        ),
    ]
