# Generated by Django 5.0.6 on 2024-07-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_organization_alter_maintenance_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='date_ordered',
            new_name='date_order',
        ),
    ]
