# Generated by Django 5.0.6 on 2024-07-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_rename_date_ordered_maintenance_date_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='type',
            new_name='type_maintenance',
        ),
    ]
