# Generated by Django 5.0.6 on 2024-07-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetype',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
