# Generated by Django 5.0.6 on 2024-07-03 16:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_failure', models.DateField(default=datetime.datetime.now)),
                ('operating_time', models.IntegerField(default=0)),
                ('description_failure', models.TextField(default='')),
                ('used_parts', models.TextField(default='')),
                ('date_recovery', models.DateField(default=datetime.datetime.now)),
                ('service_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_service_company', to='accounts.servicecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle')),
                ('node_failure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.failurenode')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.recoverymethod')),
            ],
        ),
    ]
