# Generated by Django 5.0.6 on 2024-07-03 16:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('sn_engine', models.CharField(default='', max_length=20)),
                ('sn_transmission', models.CharField(default='', max_length=20)),
                ('sn_drive_axle', models.CharField(default='', max_length=20)),
                ('sn_steering_axle', models.CharField(default='', max_length=20)),
                ('contract', models.CharField(default='', max_length=200)),
                ('shipping_date', models.DateField(default=datetime.datetime.now)),
                ('consignee', models.CharField(default='', max_length=200)),
                ('delivery_address', models.CharField(default='', max_length=500)),
                ('equipment', models.CharField(default='', max_length=200)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_as_client', to=settings.AUTH_USER_MODEL)),
                ('drive_axle_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vehicle.driveaxlemodel')),
                ('engine_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vehicle.enginemodel')),
                ('service_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_as_service_company', to='accounts.servicecompany')),
                ('steering_axle_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vehicle.steeringaxlemodel')),
                ('transmission_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vehicle.transmissionmodel')),
                ('vehicle_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehiclemodel')),
            ],
        ),
    ]
